### ISSUE TITLE
comentarios README avance 3

### ISSUE THREAD

**Issue by AliciaMstt** [jorgecruzn/ProyectoFinalBioinf2018-II#3]
Hola Jorge,

Tu readme no lo guardaste como .md por lo que no se ve bien. Cambia el nombre del archivo para agregar .md y que github lo reconozca como un markdwon.

Tu README aún está muy incompleto, no solo debes enlistar qué es lo que hay, sino qué hace cada script y cuál es el objetivo general de los datos y scripts que están en este repositorio.

Por favor contesta a este issue  EN EL RECUADRO DE AQUÍ ABAJO DANDO CLICK EN COMMENT, no en otro issue aparte como la vez pasada.

**Comment by jorgecruzn** [comment]
Ok, gracias

Jorge
